version: "3.3"

services:
  portainer:
    image: "portainer/portainer-ce"
    restart: always
    expose: 9000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    labels:
      - "traefik.http.routers.portainer.rule=Host(`${PORTAINER_DOMAIN}`)" 
      - "traefik.http.routers.portainer.middlewares=auth"
      - "traefik.http.routers.portainer.tls.certresolver=le"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
volumes:
  portainer_data