version: "3.3"

services:

  traefik:
    image: "traefik:v2.0.0"
    restart: always
    command:
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.address=:80
      - --providers.docker=true
      - --api
      - --certificatesresolvers.le.acme.email=${DOMAIN_EMAIL}
      - --certificatesresolvers.le.acme.storage=/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "../data/acme.json:/acme.json"
    labels:
      # Dashboard
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=admin"
      - "traefik.http.routers.traefik.tls.certresolver=le"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.middlewares.admin.basicauth.users=${TRAEFIK_ADMIN_HTPW}"
      # Auth
      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_BASIC_AUTH_HTPW}"
      # Redirects
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"
  
  db:
    image: "mysql:5.7"
    volumes:
      - "db_data:/var/lib/mysql"
      - "../data/sql_backup:/backups"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
      MYSQL_DATABASE: ${WP_DB}
      MYSQL_USER: ${WP_DB_USER}
      MYSQL_PASSWORD: ${WP_DB_PW}

  wordpress:
    depends_on:
      - db
    image: "wordpress:latest"
    labels:
      - "traefik.http.routers.wordpress.rule=Host(`${WP_DOMAIN}`)" 
      - "traefik.http.routers.wordpress.middlewares=auth"
      - "traefik.http.routers.wordpress.tls.certresolver=le"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
    restart: always
    volumes:
      - "wp_data:/var/www/html"
      - "/server/data/wp_backup:/backups"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WP_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WP_DB_PW}
      WORDPRESS_DB_NAME: ${WP_DB}

volumes:
  db_data:
  wp_data: 
